spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-autp: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    